name: hipp2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=18_linux64_openblas
  - libcblas=3.9.0=18_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - liblapack=3.9.0=18_linux64_openblas
  - libnsl=2.0.0=hd590300_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - numpy=1.26.0=py39h474f0d3_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - python_abi=3.9=4_cp39
  - readline=8.2=h8228510_1
  - scipy=1.11.3=py39h474f0d3_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - attrs==21.4.0
      - aussel-model==0.0.0
      - bidict==0.22.1
      - brian2==2.5.4
      - cleosim==0.10.0
      - contourpy==1.1.1
      - cycler==0.12.0
      - cython==3.0.3
      - fonttools==4.43.0
      - importlib-resources==6.1.0
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - ldsctrlest==0.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - neo==0.12.0
      - nptyping==1.4.4
      - packaging==23.2
      - pillow==10.0.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - quantities==0.14.1
      - six==1.16.0
      - sympy==1.12
      - tklfp==0.2.0
      - typish==1.9.3
      - zipp==3.17.0
